# Generated by Django 4.1.3 on 2022-12-06 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_feed_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AddConstraint(
            model_name='feed',
            constraint=models.UniqueConstraint(fields=('name', 'owner'), name='unique name and owner bond'),
        ),
    ]
