# Generated by Django 4.1.3 on 2023-01-06 16:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0005_alter_data_value_alter_feed_name_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='name',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9-_.]+$', 'Feeds name contains invalid character.')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9-_.]+$', 'Username contains invalid character.')], verbose_name='username'),
        ),
    ]
