# Generated by Django 4.1.3 on 2023-02-08 18:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0006_alter_feed_name_alter_user_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AddField(
            model_name='user',
            name='username_original',
            field=models.CharField(default='0', max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9-_.]+$', 'Username contains invalid character.')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^[a-z0-9-_.]+$', 'Lowered username contains invalid character.')], verbose_name='username'),
        ),
    ]
