# Generated by Django 4.1.7 on 2023-03-21 18:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0009_alter_data_date_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='username_original',
            new_name='display_name',
        ),
        migrations.AlterField(
            model_name='data',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
